name: Dipp Echo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49317
title: Dipp Echo Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#cc3333'
    - '#1a0608'
    - '#731d1d'
    - '#4d1314'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.15287662320770323
purpose: []
