name: Dipp Echo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49317
title: Dipp Echo Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#666666'
    - '#000000'
    - '#333333'
    - '#c08110'
    - '#ffffff'
  brandStrength: 0.7345330589450896
  lightness: 0.5471312878653407
  saturation: 0.7601858645211905
  rhythmicContrast: 0.15287662320770323
purpose: []
